alert('welcome to the JavaScript calculater(by binyamin)');
document.write('<h1>would you like to multiply,add,subtract,or divide?</h1>');
document.write('<label for="divide"><h2>divide</h2></label><input type="radio" id="divide" >');
document.write('<label for="add"><h2>add</h2></label><input type="radio" id="add" >');
document.write('<label for="subtract"><h2>subtract</h2></label><input type="radio" id="subtract" >');
document.write('<label for="multiply"><h2>multiply</h2></label><input type="radio" id="multiply" >');
var input1 = prompt('please type a number');
parseInt(input1);
var input2 = prompt('please another type a number');
parseInt(input2);
